#!/usr/bin/env bash
# Bash script to install Nginx

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# configure nginx and create index.html file
ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Restart Nginx
sudo service nginx restart
