#!/usr/bin/env bash
# Bash script to install and configure Nginx

# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Create directory and index.html file
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Configure Nginx
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
