#!/usr/bin/env bash
# Bash script to configure Nginx for redirection

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create directory and index.html file
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# add a location block for the redirection
sudo bash -c 'cat <<EOL >> /etc/nginx/sites-available/default

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
EOL'

# Restart Nginx
sudo service nginx restart
