#!/usr/bin/env bash
# Bash script to configure Nginx with a custom 404 page

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create directory and index.html file
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Create the custom 404 page
sudo sh -c 'echo "Ceci n'"'"'est pas une page." > /var/www/html/404.html'

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat <<EOL >> /etc/nginx/sites-available/default

error_page 404 /404.html;

location = /404.html {
    internal;
}
EOL'

# Restart Nginx
sudo service nginx restart
