#!/usr/bin/env bash
# Bash script to install and configure Nginx

# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Create directory and index.html file
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
         return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ/;
     }

     error_page 404 /404.html;

     location = /404.html {
         root /etc/nginx/html;
     }
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
