#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Define the configuration in a variable
haproxy_config=$(cat <<EOF
frontend my_frontend
    bind *:80
    default_backend alx_backend

backend alx_backend
    balance roundrobin
    server 374232-web-01 34.232.72.195:80 check
    server 374232-web-02 34.229.55.94:80 check
EOF
)

# Add the configuration to haproxy.cfg
echo -e "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy service
sudo systemctl restart haproxy
