#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install --no-install-recommends -y software-properties-common
echo | sudo add-apt-repository ppa:vbernat/haproxy-2.8

sudo apt-get install -y haproxy=2.8.\*

# Configure HAProxy

haproxy_config="frontend main
    bind *:80
    default_backend webservers

backend webservers
    server 374232-web-01 34.232.72.195:80
    server 374232-web-02 34.229.55.94:80"

# Enable HAProxy init script
sudo sed -i '36r /dev/stdin' /etc/haproxy/haprox.cfg <<< "$haproxy_config"

# Restart HAProxy service
sudo service haproxy restart
