#!/usr/bin/env bash
# This script displays information about users from the /etc/passwd file using the while loop and IFS.

while IFS=':' read -r username _ uid gid _ home shell; do
  read -r _ _ _ info <<< $(getent passwd "$username")
  read -r _ _ _ _ _ _ _ password <<< "$info"
  
  echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
  echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
  echo
done < /etc/passwd
