#!/usr/bin/env bash
# This is the ssh client system-wide configuration file.
# This file provides defaults for users, and the values
# can be changed in per-user configuration files or on the command line.

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
